### ISSUE TITLE
Try switching turtle to CircleCI as a pilot project

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/turtle#16]
As turtle has low development activity, it should be fine with 1500 minute limit of unpaid CircleCI subscription. We can see how it goes after.

Looking for green light from @leandro-lucarella-sociomantic (== enabling CircleCI for the repo administratively)

FYI @sociomantic-tsunami/core-team

**Comment by leandro-lucarella-sociomantic** [comment]
Did I do anything for ocean? I can't see anything in circleci dashboard...

**Comment by mihails-strasuns-sociomantic** [comment]
No, I did ocean experiments inside my own personal fork (https://github.com/mihails-strasuns/ocean/pull/1)

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, OK, can you post a link to the docs on the setup procedure?

**Comment by mihails-strasuns-sociomantic** [comment]
https://circleci.com/docs/2.0/first-steps - afaiu you should simply log in with `sociomantictsunami` account and give it permissions, after that any repo that gets yml config file will be tested automatically.

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/turtle/pull/17 adds a basic yml script, will wait until it starts being tested :angel:

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, I already signed up before I think, maybe I didn't approved it then and now I can't find a way to add a new org. :unamused:

**Comment by leandro-lucarella-sociomantic** [comment]
OK, going through the signup again seemed to do the trick.

**Comment by mihails-strasuns-sociomantic** [comment]
I think you also need to explicitly do "Add Project" in the UI to start testing turtle repo

**Comment by leandro-lucarella-sociomantic** [comment]
OK, enabled.

**Comment by leandro-lucarella-sociomantic** [comment]
If this is only about enabling, then please close, if not and there is anything else needed from me, please unassign me :)

**Comment by mihails-strasuns-sociomantic** [comment]
Does not seem to pick up PR but I can now access turtle settings in circleCI dashboard so will try to fix it myself.

**Comment by leandro-lucarella-sociomantic** [comment]
I had to explicitly enable PRs from forks. It seems reasonable to have a limit on it because a troll could spend all your minutes by sending spurious PRs. It seems to be lacking a filter to only test PRs from org members, which is probably the most sane option.

**Comment by leandro-lucarella-sociomantic** [comment]
I consider this to be an ongoing issue as long as CircleCI is being tested. I don't want to have only one rogue project using CircleCI forever, so I will keep this open as a reminder that this is still in testing/experimental stage.

**Comment by mihails-strasuns-sociomantic** [comment]
NP, I have re-labeled it accordingly.

**Comment by mihails-strasuns-sociomantic** [comment]
I think this can be considered done. Conclusion - it is better than travis but not enough to warrant switch, especially now that we aim towards GitLab. Biggest problem was lack of ergonomic DRY definition of build stages.
