### ISSUE TITLE
Add project to dlang's Jenkins

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/turtle#46]
Similarly to what [we already have with Ocean](https://github.com/dlang/ci/blob/f4316788faaf0202c4f87e6926694fc6e0d2f19a/vars/runPipeline.groovy#L276-L282), we should add all other open source projects to [dlang Jenkins](https://ci.dlang.io) to make sure new DMDs don't break them.

**Comment by mihails-strasuns** [comment]
https://github.com/dlang/ci/pull/382

**Comment by leandro-lucarella-sociomantic** [comment]
I guess you already know, but it's failing.

**Comment by mihails-strasuns** [comment]
```
[turtle    ] Temporary sandbox created at '/var/lib/buildkite-agent/builds/ci-agent-e230b12e-1a84-4f67-a52c-9d4a50796458-3/dlang/ci/build/sociomantic-tsunami-turtle/build/devel/tmp/sandbox-dummy_daemon-XXTsmHvG/'
core.exception.AssertError@./submodules/ocean/src/ocean/stdc/posix/sys/un.d(46): Can't set path longer than UNIX_PATH_MAX
```

This may end up being painful.

**Comment by mihails-strasuns** [comment]
https://github.com/sociomantic-tsunami/turtle/pull/65

**Comment by mihails-strasuns** [comment]
Upstream PR merged.
