### ISSUE TITLE
Irregular `Tested application kept running even after SIGABRT` test suite failures

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/turtle#47]
With at least one of our applications we have been seeing test failures related to the tested app not shutting down correctly when SIGABRT is issued:

```
09:30:55 [turtle    ] Tested application kept running even after SIGABRT
09:30:56 core.exception.AssertError@./submodules/turtle/src/turtle/application/model/TestedApplicationBase.d(275): Assertion failure
09:30:56 ----------------
09:30:56 src/core/exception.d:434 _d_assert [0xe9d827]
09:30:56 ??:? void turtle.application.model.TestedApplicationBase.__assert(int) [0xdd92a4]
09:30:56 ./submodules/turtle/src/turtle/application/model/TestedApplicationBase.d:275 bool turtle.application.model.TestedApplicationBase.KillTimerEvent.nextSignal() [0xdd9114]
```

The two observed cases so far impacted D2 builds only, so it could be that this is a D2-only issue.

The app for which this was observed does have some functionality that uses `ocean.task.util.Timer.wait` to temporarily suspend tasks, but I can't see how this could reasonably interfere with SIGABRT: there isn't any custom-written signal handling, and it uses the `DaemonApp` `TaskExt` extension (so signal handling should be automatically set up under the hood).

Requesting a fresh test run usually results in success, so this is not a consistent failure.

**Comment by mihails-strasuns-sociomantic** [comment]
What happens if you send SIGABRT to your app manually (`kill -6 <pid>`)?

**Comment by joseph-wakeling-sociomantic** [comment]
First attempts, it always seems to just abort immediately.  But this is a very basic case where the app is not actually "busy" (I didn't set up a DHT for it to work with).

**Comment by joseph-wakeling-sociomantic** [comment]
I've also tried issuing a `SIGABRT` to the tested app mid-integration-test-run, and again, it seems to shut down immediately.

BTW, the test suite has some special-casing to handle the fact that the app may `wait` up to 5 seconds for a task to complete.  I tried removing this, and it doesn't seem to create any problems for the app to shut down.

That said, I don't think I've ever seen this failure in a local test run, only in CI.

**Comment by nemanja-boric-sociomantic** [comment]
I do wonder if the D2 runtime is blocking the signal dispatch while in GC cycle or something similar, where the application will not be able to react to `SIGABRT`.

**Comment by nemanja-boric-sociomantic** [comment]
Here's one such place where the all signals except the resume signal are masked:

https://github.com/dlang/druntime/blob/86cd40a036a67d9b1bff6c14e91cba1e5557b119/src/core/thread.d#L446-L456

**Comment by mihails-strasuns-sociomantic** [comment]
Current guess is that because of that GC intervention default turtle wait time of 0.1 seconds is not enough. New https://github.com/sociomantic-tsunami/turtle/pull/48 PR allows to configure final wait time from the test suite to be able to confirm this suspicion.

**Comment by mihails-strasuns-sociomantic** [comment]
Closing for now, please reopen if issue still manifests with increased wait time
