### ISSUE TITLE
Start testing with dmd-transitional 2.071.s*

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/turtle#8]

**Comment by mathias-lang-sociomantic** [comment]
That's done: https://github.com/sociomantic-tsunami/turtle/blob/a79585dd45c73fa9eaaabb12a2eac228bf88257e/.circleci/config.yml#L11-L12

**Comment by mihails-strasuns-sociomantic** [comment]
Oops, looks like I did it accidentally ^_^
