### ISSUE TITLE
D2: Automatically convert tags and push them

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/turtle#9]
To move forward with D2 we need to provide automatically converted libraries for projects that are built only for D2.

Every time a new tag is pushed, we have to convert it to D2, tag the converted version with a `+d2` build metadata information appended (so tag `v2.3.4` --- conversion D2 ---> `v2.3.4+d2`) and push it back (making sure the new tag is not converted again!).

This capability will be probably [added to beaver](https://github.com/sociomantic-tsunami/beaver/issues/7), but at some point we need to use that feature from beaver here.

**Comment by leandro-lucarella-sociomantic** [comment]
It would be nice to add this sooner than later.

**Comment by mihails-strasuns-sociomantic** [comment]
I will likely proceed with existing non-DRY approach of https://github.com/sociomantic-tsunami/turtle/pull/30 but don't want to block ocean v4 release chain on it.

**Comment by leandro-lucarella-sociomantic** [comment]
This seems to be merged now!

**Comment by mihails-strasuns-sociomantic** [comment]
Yeah, I will tag turtle release with just that change to trigger conversion next week.

**Comment by leandro-lucarella-sociomantic** [comment]
Reopening until we get at least some tag converted (ideally all maintained branches should have a tag converted).

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/turtle/releases/tag/v9.1.1%2Bd2
https://github.com/sociomantic-tsunami/turtle/releases/tag/v8.4.0%2Bd2
